"""Research-source wording aliases for active rental-taxonomy paths.

This data-only module is generated from
``docs/rental_research_coverage_2026-10-03.json``.  It deliberately excludes
review-gated, kit-only, and rental-mode-only rows: only terms that can resolve
to an active catalog path belong here.
"""

from __future__ import annotations

# Key: (category, subcategory) or (category, subcategory, third_level).
# Value: supplied research labels that should discover that canonical path.
RESEARCH_PATH_ALIASES: dict[tuple[str, ...], tuple[str, ...]] = {
    ('Agriculture & Landscaping', 'Lawn & Garden', 'Aerators'): ('Lawn aerator',),
    ('Agriculture & Landscaping', 'Lawn & Garden', 'Broadcast Seed Spreaders'): ('Broadcast seed spreader',),
    ('Agriculture & Landscaping', 'Lawn & Garden', 'Hedge Cutters'): ('Hedge cutter',),
    ('Agriculture & Landscaping', 'Lawn & Garden', 'Lawn Dethatchers'): ('Lawn dethatcher',),
    ('Agriculture & Landscaping', 'Lawn & Garden', 'Mowers'): ('Brush mower',),
    ('Agriculture & Landscaping', 'Lawn & Garden', 'Sod Cutters'): ('Sod cutter',),
    ('Agriculture & Landscaping', 'Small-Harvest Processing', 'Apple Crushers'): ('Apple crusher',),
    ('Agriculture & Landscaping', 'Small-Harvest Processing', 'Apple Presses'): ('Apple press',),
    ('Agriculture & Landscaping', 'Small-Harvest Processing', 'Honey Extractor Kits'): ('Honey extractor kit',),
    ('Agriculture & Landscaping', 'Small-Harvest Processing', 'Orchard Tripod Ladders'): ('Orchard tripod ladder',),
    ('Agriculture & Landscaping', 'Tractors & Implements', 'Agricultural Trailers'): ('Agricultural trailer',),
    ('Agriculture & Landscaping', 'Tractors & Implements', 'Post-Hole Borers'): ('Post-hole borer',),
    ('Agriculture & Landscaping', 'Tractors & Implements', 'Seeders'): ('Slit seeder',),
    ('Agriculture & Landscaping', 'Tractors & Implements', 'Tractors'): ('Tractor',),
    ('Agriculture & Landscaping', 'Tractors & Implements', 'Utility Terrain Vehicles'): ('Utility terrain vehicle',),
    ('Baby & Kids', 'Nursery & Sleep', 'Baby Swings'): ('Baby swing',),
    ('Baby & Kids', 'Nursery & Sleep', 'Bouncers'): ('Bouncer',),
    ('Baby & Kids', 'Nursery & Sleep', 'Cribs'): ('Crib',),
    ('Baby & Kids', 'Nursery & Sleep', 'High Chairs'): ('High chair',),
    ('Baby & Kids', 'Toys & Play', 'Toys, Books & Games Kits'): ('Toys books and games kit',),
    ('Baby & Kids', 'Travel & Safety', 'Car Seats'): ('Car seat',),
    ('Baby & Kids', 'Travel & Safety', 'Child Wagons'): ('Child wagon',),
    ('Baby & Kids', 'Travel & Safety', 'Strollers'): ('Stroller',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Concrete Buckets'): ('Concrete bucket',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Concrete Buggies'): ('Concrete buggy',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Concrete Floor Saws'): ('Concrete floor saw',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Concrete Mixers'): ('Concrete mixer',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Concrete Scarifiers'): ('Concrete scarifier',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Concrete Vibrators'): ('Concrete vibrator',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Diamond Core Drills'): ('Diamond core drill',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Masonry Saws'): ('Masonry saw',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Mortar Mixers'): ('Mortar mixer',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Portable Shot Blasters'): ('Portable shot blaster',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Rebar Benders'): ('Rebar bender',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Rebar Cutters'): ('Rebar cutter',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Rebar Tying Tools'): ('Rebar tying tool',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Tile Saws'): ('Tile saw',),
    ('Construction & Industrial Equipment', 'Concrete & Masonry', 'Trowels'): ('Power trowel',),
    ('Construction & Industrial Equipment', 'Geotextile & Site Textile Tools', 'Portable Geotextile Sewing Machines'): ('Portable geotextile sewing machine',),
    ('Construction & Industrial Equipment', 'Hydraulic Maintenance Tools', 'Hollow-Plunger Hydraulic Cylinders'): ('Hollow-plunger hydraulic cylinder',),
    ('Construction & Industrial Equipment', 'Hydraulic Maintenance Tools', 'Hydraulic Cutterheads'): ('Hydraulic cutterhead',),
    ('Construction & Industrial Equipment', 'Hydraulic Maintenance Tools', 'Hydraulic Electric Pumps'): ('Hydraulic electric pump',),
    ('Construction & Industrial Equipment', 'Hydraulic Maintenance Tools', 'Hydraulic Hand Pumps'): ('Hydraulic hand pump',),
    ('Construction & Industrial Equipment', 'Hydraulic Maintenance Tools', 'Hydraulic Nut Splitters'): ('Hydraulic nut splitter',),
    ('Construction & Industrial Equipment', 'Hydraulic Maintenance Tools', 'Hydraulic Punches'): ('Hydraulic punch',),
    ('Construction & Industrial Equipment', 'Hydraulic Maintenance Tools', 'Hydraulic Torque Wrenches'): ('Hydraulic torque wrench',),
    ('Construction & Industrial Equipment', 'Hydraulic Maintenance Tools', 'Lock-Nut Hydraulic Cylinders'): ('Lock-nut hydraulic cylinder',),
    ('Construction & Industrial Equipment', 'Hydraulic Maintenance Tools', 'Low-Height Hydraulic Cylinders'): ('Low-height hydraulic cylinder',),
    ('Construction & Industrial Equipment', 'Hydraulic Maintenance Tools', 'Pancake Hydraulic Cylinders'): ('Pancake hydraulic cylinder',),
    ('Construction & Industrial Equipment', 'Trench & Shoring', 'Bedding Boxes'): ('Bedding box',),
    ('Construction & Industrial Equipment', 'Trench & Shoring', 'Composite Trench Covers'): ('Composite trench cover',),
    ('Construction & Industrial Equipment', 'Trench & Shoring', 'Davit & Tripod Retrieval Systems'): ('Davit or tripod retrieval system',),
    ('Construction & Industrial Equipment', 'Trench & Shoring', 'Ground Protection Mats'): ('Ground protection mat',),
    ('Construction & Industrial Equipment', 'Trench & Shoring', 'Manhole Braces'): ('Manhole brace',),
    ('Construction & Industrial Equipment', 'Trench & Shoring', 'Manhole Vacuum Testers'): ('Manhole vacuum tester',),
    ('Construction & Industrial Equipment', 'Trench & Shoring', 'Steel Road Plates'): ('Steel road plate',),
    ('Construction & Industrial Equipment', 'Trench & Shoring', 'Temporary Guardrails'): ('Temporary guardrail',),
    ('Construction & Industrial Equipment', 'Trench & Shoring', 'Trench Bridges'): ('Trench bridge',),
    ('Construction & Industrial Equipment', 'Trench & Shoring', 'Trench Shields'): ('Trench shield',),
    ('Construction & Industrial Equipment', 'Welding & Fabrication', 'Orbital Welding Systems'): ('Orbital welding system',),
    ('Construction & Industrial Equipment', 'Welding & Fabrication', 'Pipe Cutting Machines'): ('Pipe cutting machine',),
    ('Construction & Industrial Equipment', 'Welding & Fabrication', 'Tube Cutting Machines'): ('Tube cutting machine',),
    ('Construction & Industrial Equipment', 'Welding & Fabrication', 'Tube Facing Machines'): ('Tube facing machine',),
    ('Construction & Industrial Equipment', 'Welding & Fabrication', 'Welding Power Sources'): ('Welding power source',),
    ('Electronics', 'Cameras & Video', 'Anamorphic Lenses'): ('Anamorphic lens',),
    ('Electronics', 'Cameras & Video', 'Broadcast Cameras'): ('Broadcast camera',),
    ('Electronics', 'Cameras & Video', 'Cinema Cameras'): ('Cinema camera',),
    ('Electronics', 'Cameras & Video', 'Cinema Prime Lenses'): ('Cinema prime lens',),
    ('Electronics', 'Cameras & Video', 'Cinema Zoom Lenses'): ('Cinema zoom lens',),
    ('Electronics', 'Cameras & Video', 'Director Viewfinders'): ('Director viewfinder',),
    ('Electronics', 'Computers & Tablets', 'Monitors'): ('Presentation monitor',),
    ('Electronics', 'Office Tech', 'Projection Screens'): ('Projection screen',),
    ('Electronics', 'Office Tech', 'Projectors'): ('Video projector',),
    ('Events & Production Equipment', 'Audio Equipment', 'Boom Poles'): ('Boom pole',),
    ('Events & Production Equipment', 'Audio Equipment', 'Lavalier Microphones'): ('Lavalier microphone',),
    ('Events & Production Equipment', 'Audio Equipment', 'Microphones'): ('Microphone',),
    ('Events & Production Equipment', 'Audio Equipment', 'Mixers'): ('Audio mixer',),
    ('Events & Production Equipment', 'Audio Equipment', 'PA Systems'): ('Conference audio system',),
    ('Events & Production Equipment', 'Audio Equipment', 'Shotgun Microphones'): ('Shotgun microphone',),
    ('Events & Production Equipment', 'Interpretation & Tour Audio', 'Interpretation Headsets'): ('Interpretation headset',),
    ('Events & Production Equipment', 'Interpretation & Tour Audio', 'Portable Tour Audio Systems'): ('Portable tour audio system',),
    ('Events & Production Equipment', 'Interpretation & Tour Audio', 'Soundproof Interpretation Booths'): ('Soundproof interpretation booth',),
    ('Events & Production Equipment', 'Interpretation & Tour Audio', 'Wireless Interpretation Receivers'): ('Wireless interpretation receiver',),
    ('Events & Production Equipment', 'Lighting Equipment'): ('Stage lighting',),
    ('Events & Production Equipment', 'Rigging & Truss', 'Pipe-and-Drape Systems'): ('Pipe-and-drape system',),
    ('Events & Production Equipment', 'Staging & Flooring', 'Stage Platforms'): ('Stage platform',),
    ('Events & Production Equipment', 'Tableware & Linen', 'Pastry & Serving Cutlery'): ('Pastry and serving cutlery',),
    ('Events & Production Equipment', 'Video & Displays', 'LED Walls'): ('LED video wall',),
    ('Events & Production Equipment', 'Video & Displays', 'Media Servers'): ('Media server',),
    ('Events & Production Equipment', 'Video & Displays', 'Video Production Systems'): ('Video production equipment',),
    ('Food & Concession Equipment', 'Commercial Kitchen Equipment', 'Catering Ovens'): ('Catering oven',),
    ('Food & Concession Equipment', 'Commercial Kitchen Equipment', 'Commercial Freezers'): ('Commercial freezer',),
    ('Food & Concession Equipment', 'Commercial Kitchen Equipment', 'Commercial Refrigerators'): ('Commercial refrigerator',),
    ('Food & Concession Equipment', 'Commercial Kitchen Equipment', 'Hot Cupboards'): ('Heated holding and proofing cabinet', 'Hot cupboard'),
    ('Food & Concession Equipment', 'Commercial Kitchen Equipment', 'Preparation Tables'): ('Preparation table',),
    ('Food & Concession Equipment', 'Cooking Equipment', 'Commercial Fryers'): ('Commercial gas deep fryer', 'Double bench fryer'),
    ('Food & Concession Equipment', 'Cooking Equipment', 'Grills & Griddles'): ('Barbecue equipment',),
    ('Food & Concession Equipment', 'Donut Equipment', 'Donut Makers'): ('Mini doughnut maker',),
    ('Food & Concession Equipment', 'Frozen & Dessert Equipment', 'Chocolate Fountains'): ('Chocolate fountain',),
    ('Food & Concession Equipment', 'Frozen & Dessert Equipment', 'Cotton Candy Machines'): ('Cotton candy machine',),
    ('Food & Concession Equipment', 'Frozen & Dessert Equipment', 'Nacho Cheese Dispensers'): ('Nacho cheese dispenser',),
    ('Food & Concession Equipment', 'Frozen & Dessert Equipment', 'Shaved Ice Machines'): ('Shaved ice machine',),
    ('Food & Concession Equipment', 'Frozen & Dessert Equipment', 'Slush Machines'): ('Slush machine',),
    ('Food & Concession Equipment', 'Frozen & Dessert Equipment', 'Soft-Serve Machines'): ('Soft-serve ice cream machine',),
    ('Food & Concession Equipment', 'Hot Dog Equipment', 'Hot Dog Rollers'): ('Hot dog roller',),
    ('Food & Concession Equipment', 'Popcorn Equipment', 'Popcorn Machines'): ('Popcorn machine',),
    ('Food & Concession Equipment', 'Serving & Beverage Equipment', 'Beverage Cooling Troughs'): ('Beverage cooling trough',),
    ('Food & Concession Equipment', 'Serving & Beverage Equipment', 'Beverage Dispensers'): ('Beverage dispenser',),
    ('Food & Concession Equipment', 'Serving & Beverage Equipment', 'Hot Chocolate Urns'): ('Hot chocolate urn',),
    ('Food & Concession Equipment', 'Serving & Beverage Equipment', 'Insulated Beverage Dispensers'): ('Insulated beverage dispenser',),
    ('Food & Concession Equipment', 'Serving & Beverage Equipment', 'Rectangular Chafing Dishes'): ('Rectangular chafing dish',),
    ('Food & Concession Equipment', 'Serving & Beverage Equipment', 'Round Roll-Top Chafing Dishes'): ('Round roll-top chafing dish',),
    ('Furniture', 'Rugs & Decor', 'Artwork Rentals'): ('Artwork rental',),
    ('Furniture', 'Rugs & Decor', 'Tropical Plant Rentals'): ('Tropical plant rental',),
    ('Hobbies & Creative Equipment', 'Arts & Crafts', 'Button Badge Press Kits'): ('Button badge press kit',),
    ('Hobbies & Creative Equipment', 'Arts & Crafts', 'Pottery Wheels'): ('Pottery wheel',),
    ('Hobbies & Creative Equipment', 'Sewing & Textile', 'Coverstitch Machines'): ('Coverstitch machine',),
    ('Hobbies & Creative Equipment', 'Sewing & Textile', 'Fabric Cutting Tables'): ('Fabric cutting table',),
    ('Hobbies & Creative Equipment', 'Sewing & Textile', 'Fabric Die-Cutting Machines'): ('Fabric die-cutting machine',),
    ('Hobbies & Creative Equipment', 'Sewing & Textile', 'Ironing Stations'): ('Ironing station',),
    ('Hobbies & Creative Equipment', 'Sewing & Textile', 'Serger Machines'): ('Overlocker or serger',),
    ('Hobbies & Creative Equipment', 'Sewing & Textile', 'Sewing Machines'): ('Sewing machine',),
    ('Marine & Watercraft', 'Boats', 'Monohull Sailboats'): ('Monohull sailboat',),
    ('Marine & Watercraft', 'Boats', 'Power Yachts'): ('Power yacht',),
    ('Marine & Watercraft', 'Boats', 'Sailing Catamarans'): ('Sailing catamaran',),
    ('Music & Performance Equipment', 'Amplification & Backline', 'Instrument Amplifiers'): ('Instrument amplifier',),
    ('Music & Performance Equipment', 'Musical Instruments', 'Bass Guitars'): ('Bass guitar',),
    ('Music & Performance Equipment', 'Musical Instruments', 'Drum Kits'): ('Drum kit',),
    ('Music & Performance Equipment', 'Musical Instruments', 'Guitars'): ('Guitar',),
    ('Music & Performance Equipment', 'Musical Instruments', 'Keyboards'): ('Keyboard or synthesizer',),
    ('Music & Performance Equipment', 'Musical Instruments', 'Orchestral Instruments'): ('Orchestral instrument',),
    ('Retail & Vending Equipment', 'Display & Merchandising', 'Display Cases'): ('Glass display cabinet',),
    ('Retail & Vending Equipment', 'Display & Merchandising', 'Mannequins'): ('Adult display mannequin', 'Child display mannequin'),
    ('Retail & Vending Equipment', 'POS & Checkout', 'Barcode Scanners'): ('Handheld barcode scanner',),
    ('Retail & Vending Equipment', 'POS & Checkout', 'Inventory Scanning Terminals'): ('Inventory scanning terminal',),
    ('Retail & Vending Equipment', 'POS & Checkout', 'POS Hardware Kits'): ('POS hardware kit',),
    ('Retail & Vending Equipment', 'POS & Checkout', 'Thermal Badge Printers'): ('Thermal badge printer',),
    ('Spaces & Studios', 'Event Venues'): ('Event space',),
    ('Spaces & Studios', 'Retail & Pop-up Spaces', 'Pop-up Retail Spaces'): ('Pop-up retail space',),
    ('Sports & Outdoors', 'Camping & Outdoors', 'Camping Equipment Kits'): ('Camping equipment kit',),
    ('Sports & Outdoors', 'Camping & Outdoors', 'Packrafts'): ('Packraft',),
    ('Sports & Outdoors', 'Camping & Outdoors', 'Sleeping Equipment Kits'): ('Sleeping equipment kit',),
    ('Sports & Outdoors', 'Camping & Outdoors', 'Tents'): ('Camping tent',),
    ('Sports & Outdoors', 'Water Sports', 'Canoes'): ('Canoe',),
    ('Sports & Outdoors', 'Water Sports', 'Kayaks'): ('Kayak',),
    ('Sports & Outdoors', 'Water Sports', 'Paddleboards'): ('Stand-up paddleboard',),
    ('Temporary Infrastructure & Site Services', 'Climate Control', 'Air Handlers'): ('Air handler',),
    ('Temporary Infrastructure & Site Services', 'Climate Control', 'Chillers'): ('Industrial chiller',),
    ('Temporary Infrastructure & Site Services', 'Climate Control', 'Cooling Towers'): ('Cooling tower',),
    ('Temporary Infrastructure & Site Services', 'Climate Control', 'Electric Heaters'): ('Electric heater',),
    ('Temporary Infrastructure & Site Services', 'Climate Control', 'Ground Heaters'): ('Ground heater',),
    ('Temporary Infrastructure & Site Services', 'Climate Control', 'Indirect-Fired Heaters'): ('Indirect-fired heater',),
    ('Temporary Infrastructure & Site Services', 'Climate Control', 'Portable Air Conditioners'): ('Portable air conditioner',),
    ('Temporary Infrastructure & Site Services', 'Climate Control', 'Spot Coolers'): ('Spot cooler',),
    ('Temporary Infrastructure & Site Services', 'Drying & Air Quality', 'Air Scrubbers'): ('Portable air scrubber',),
    ('Temporary Infrastructure & Site Services', 'Drying & Air Quality', 'Carpet Dryers & Air Movers'): ('Carpet dryer or air mover',),
    ('Temporary Infrastructure & Site Services', 'Drying & Air Quality', 'Desiccant Dehumidifiers'): ('Desiccant dehumidifier',),
    ('Temporary Infrastructure & Site Services', 'Drying & Air Quality', 'Industrial Fans'): ('High-volume fan',),
    ('Temporary Infrastructure & Site Services', 'Drying & Air Quality', 'Refrigerant Dehumidifiers'): ('Refrigerant dehumidifier',),
    ('Temporary Infrastructure & Site Services', 'Mobile Offices & Structures', 'Mobile Offices'): ('Mobile office',),
    ('Temporary Infrastructure & Site Services', 'Mobile Offices & Structures', 'Temporary Structures'): ('Temporary industrial tent',),
    ('Temporary Infrastructure & Site Services', 'Power Generation', 'Battery Storage'): ('Battery energy storage system',),
    ('Temporary Infrastructure & Site Services', 'Power Generation', 'Generators'): ('Portable generator', 'Diesel generator', 'Natural-gas generator'),
    ('Temporary Infrastructure & Site Services', 'Power Generation', 'Load Banks'): ('Resistive load bank', 'Resistive-reactive load bank'),
    ('Temporary Infrastructure & Site Services', 'Power Generation', 'Power Distribution Panels'): ('Power distribution panel',),
    ('Temporary Infrastructure & Site Services', 'Power Generation', 'Temporary Power Cables'): ('Temporary power cable',),
    ('Temporary Infrastructure & Site Services', 'Power Generation', 'Transfer Switches'): ('Transfer switch',),
    ('Temporary Infrastructure & Site Services', 'Power Generation', 'Transformers'): ('Transformer',),
    ('Temporary Infrastructure & Site Services', 'Pumps & Water Management', 'Dewatering Pumps'): ('Trash or dewatering pump',),
    ('Temporary Infrastructure & Site Services', 'Pumps & Water Management', 'Diaphragm Pumps'): ('Diaphragm pump',),
    ('Temporary Infrastructure & Site Services', 'Pumps & Water Management', 'Fluid Storage Tanks'): ('Fluid storage tank',),
    ('Temporary Infrastructure & Site Services', 'Pumps & Water Management', 'Water Treatment Units'): ('Industrial water filtration equipment',),
    ('Temporary Infrastructure & Site Services', 'Sanitation', 'Handwash Stations'): ('Handwashing station',),
    ('Temporary Infrastructure & Site Services', 'Sanitation', 'Mobile Showers'): ('Mobile shower',),
    ('Temporary Infrastructure & Site Services', 'Sanitation', 'Portable Toilets'): ('Portable toilet',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'Cable Locators'): ('Cable locator',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'Clamp Meters'): ('Clamp meter',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'Electronic Loads'): ('Electronic load',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'Ground Resistance Testers'): ('Ground resistance tester',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'High-Voltage Meters'): ('High-voltage meter',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'Hipot Testers'): ('Hipot tester',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'Insulation Resistance Testers'): ('Insulation resistance tester',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'Low-Resistance Ohmmeters'): ('Low-resistance ohmmeter',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'Network Cable Testers'): ('Network cable tester',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'Phase Meters'): ('Phase meter',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'Power Analyzers'): ('Power analyzer',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'RF Amplifiers'): ('RF amplifier',),
    ('Test & Measurement Equipment', 'Electrical Test Instruments', 'Solar PV Testers'): ('Solar PV tester',),
    ('Test & Measurement Equipment', 'Environmental Monitoring', 'Flow Probes'): ('Flow probe',),
    ('Test & Measurement Equipment', 'Environmental Monitoring', 'Gas Detectors'): ('Gas detector',),
    ('Test & Measurement Equipment', 'Environmental Monitoring', 'Noise & Sound Meters'): ('Noise or sound meter',),
    ('Test & Measurement Equipment', 'Environmental Monitoring', 'PID Detectors'): ('PID detector',),
    ('Test & Measurement Equipment', 'Environmental Monitoring', 'Pressure Transducers'): ('Pressure transducer',),
    ('Test & Measurement Equipment', 'Environmental Monitoring', 'Water Quality Meters'): ('Water quality meter',),
    ('Test & Measurement Equipment', 'Environmental Monitoring', 'Water-Level Meters'): ('Water-level meter',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Automotive Inspection Borescopes'): ('Automotive inspection borescope',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Battery Boosters'): ('Battery booster',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Battery Chargers'): ('Battery charger',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Battery Testers'): ('Battery tester',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Cooling-System Pressure Testers'): ('Cooling-system pressure tester',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Engine Stands'): ('Engine stand',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Hydraulic Body Repair Kits'): ('Hydraulic body repair kit',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Impact Wrenches'): ('Impact wrench',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Large Socket & Ratchet Sets'): ('Large socket and ratchet set',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Tailpipe Expanders'): ('Tailpipe expander',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Torque Wrenches'): ('Torque wrench',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Transmission Jacks'): ('Transmission jack',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Ultrasonic Cleaners'): ('Ultrasonic cleaner',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Valve Spring Compressors'): ('Valve spring compressor',),
    ('Tools & Equipment', 'Automotive Workshop Tools', 'Vibratory Tumblers'): ('Vibratory tumbler',),
    ('Tools & Equipment', 'Cleaning & Restoration Equipment', 'Carpet Extractors'): ('Carpet extractor',),
    ('Tools & Equipment', 'Cleaning & Restoration Equipment', 'Cold-Water Pressure Washers'): ('Cold-water pressure washer',),
    ('Tools & Equipment', 'Cleaning & Restoration Equipment', 'Floor Polishers'): ('Floor polisher',),
    ('Tools & Equipment', 'Cleaning & Restoration Equipment', 'Handheld Sweepers'): ('Handheld sweeper',),
    ('Tools & Equipment', 'Cleaning & Restoration Equipment', 'Hot-Water Pressure Washers'): ('Hot-water pressure washer',),
    ('Tools & Equipment', 'Cleaning & Restoration Equipment', 'Ride-On Scrubbers'): ('Ride-on scrubber',),
    ('Tools & Equipment', 'Cleaning & Restoration Equipment', 'Ride-On Sweepers'): ('Ride-on sweeper',),
    ('Tools & Equipment', 'Cleaning & Restoration Equipment', 'Walk-Behind Scrubbers'): ('Walk-behind scrubber',),
    ('Tools & Equipment', 'Cleaning & Restoration Equipment', 'Walk-Behind Sweepers'): ('Walk-behind sweeper',),
    ('Tools & Equipment', 'Cleaning & Restoration Equipment', 'Wet & Dry Vacuums'): ('Wet and dry vacuum',),
    ('Tools & Equipment', 'Floor Installation & Removal', 'Carpet Knee Kickers'): ('Carpet knee kicker',),
    ('Tools & Equipment', 'Floor Installation & Removal', 'Concrete Floor Grinders'): ('Concrete floor grinder',),
    ('Tools & Equipment', 'Floor Installation & Removal', 'Drum Floor Sanders'): ('Drum floor sander',),
    ('Tools & Equipment', 'Floor Installation & Removal', 'Dust Extractors'): ('Dust extractor',),
    ('Tools & Equipment', 'Floor Installation & Removal', 'Floor Edge Sanders'): ('Floor edge sander',),
    ('Tools & Equipment', 'Floor Installation & Removal', 'Floor Stripping Machines'): ('Floor stripping machine',),
    ('Tools & Equipment', 'Floor Installation & Removal', 'Hardwood Floor Nailers'): ('Hardwood floor nailer',),
    ('Tools & Equipment', 'Floor Installation & Removal', 'Orbital Floor Sanders'): ('Orbital floor sander',),
    ('Tools & Equipment', 'Floor Installation & Removal', 'Tile Cutters'): ('Tile cutter',),
    ('Tools & Equipment', 'Floor Installation & Removal', 'Vinyl Flooring Cutters'): ('Vinyl flooring cutter',),
    ('Tools & Equipment', 'Plumbing & Pipe Tools', 'Flange Spreaders'): ('Flange spreader',),
    ('Tools & Equipment', 'Plumbing & Pipe Tools', 'Pipe Benders'): ('Pipe bender',),
    ('Tools & Equipment', 'Plumbing & Pipe Tools', 'Pipe Crimping Tools'): ('Pipe crimping tool',),
    ('Tools & Equipment', 'Plumbing & Pipe Tools', 'Pipe Cutters'): ('Pipe cutter',),
    ('Tools & Equipment', 'Plumbing & Pipe Tools', 'Pipe Freezing Machines'): ('Pipe freezing machine',),
    ('Tools & Equipment', 'Plumbing & Pipe Tools', 'Pipe Plugs'): ('Pipe plug',),
    ('Tools & Equipment', 'Plumbing & Pipe Tools', 'Pipe Threading Machines'): ('Pipe threading machine',),
    ('Tools & Equipment', 'Plumbing & Pipe Tools', 'Sewer Inspection Cameras'): ('Sewer inspection camera',),
    ('Tools & Equipment', 'Power Tools', 'Angle Grinders'): ('Angle grinder',),
    ('Tools & Equipment', 'Power Tools', 'Band Saws'): ('Band saw',),
    ('Tools & Equipment', 'Power Tools', 'Belt Sanders'): ('Belt sander',),
    ('Tools & Equipment', 'Power Tools', 'Circular Saws'): ('Circular saw',),
    ('Tools & Equipment', 'Power Tools', 'Electric Planers'): ('Electric planer',),
    ('Tools & Equipment', 'Power Tools', 'Heat Guns'): ('Heat gun',),
    ('Tools & Equipment', 'Power Tools', 'Magnetic Drills'): ('Magnetic drill',),
    ('Tools & Equipment', 'Power Tools', 'Metal Shears & Nibblers'): ('Metal shear or nibbler',),
    ('Tools & Equipment', 'Power Tools', 'Miter Saws'): ('Miter saw',),
    ('Tools & Equipment', 'Power Tools', 'Orbital Sanders'): ('Orbital sander',),
    ('Tools & Equipment', 'Power Tools', 'Reciprocating Saws'): ('Reciprocating saw',),
    ('Tools & Equipment', 'Power Tools', 'Routers'): ('Router',),
    ('Tools & Equipment', 'Power Tools', 'Table Saws'): ('Table saw',),
    ('Tools & Equipment', 'Surveying & Inspection', '3D Laser Scanners'): ('3D laser scanner',),
    ('Tools & Equipment', 'Surveying & Inspection', 'Automatic Optical Levels'): ('Automatic optical level',),
    ('Tools & Equipment', 'Surveying & Inspection', 'Digital Levels'): ('Digital level',),
    ('Tools & Equipment', 'Surveying & Inspection', 'GNSS Survey Receivers'): ('GNSS survey receiver',),
    ('Tools & Equipment', 'Surveying & Inspection', 'Laser Levels'): ('Rotating laser level',),
    ('Tools & Equipment', 'Surveying & Inspection', 'Pipe Lasers'): ('Pipe laser',),
    ('Tools & Equipment', 'Surveying & Inspection', 'Robotic Total Stations'): ('Robotic total station',),
    ('Tools & Equipment', 'Surveying & Inspection', 'Total Stations'): ('Manual total station',),
    ('Tools & Equipment', 'Surveying & Inspection', 'Underground Utility Detectors'): ('Underground utility detector',),
    ('Vehicles', 'Vehicle Travel Accessories', 'Roof Cargo Boxes'): ('Roof cargo box',),
    ('Warehousing & Logistics', 'Packaging & Labeling', 'Label Printers'): ('Thermal label printer',),
    ('Warehousing & Logistics', 'Packaging & Labeling', 'Stretch Wrappers'): ('Pallet stretch wrapper',),
    ('Warehousing & Logistics', 'Packaging & Labeling', 'Vacuum Packaging Machines'): ('Vacuum packaging machine',),
    ('Warehousing & Logistics', 'Pallet & Manual Handling', 'Air-Cushion Appliance Lifters'): ('Air-cushion appliance lifter',),
    ('Warehousing & Logistics', 'Pallet & Manual Handling', 'Dollies'): ('Appliance dolly', 'Heavy-duty inflatable-equipment dolly', 'Four-wheel furniture dolly', 'Three-wheel furniture dolly set'),
    ('Warehousing & Logistics', 'Pallet & Manual Handling', 'Hand Trucks'): ('Utility hand truck',),
    ('Warehousing & Logistics', 'Pallet & Manual Handling', 'Powered Stair-Climbing Dollies'): ('Powered stair-climbing dolly',),
    ('Warehousing & Logistics', 'Pallet & Manual Handling', 'Tree Dollies'): ('Tree dolly',),
    ('Warehousing & Logistics', 'Storage & Containers', 'Mobile Storage Containers'): ('Storage container',),
    ('Warehousing & Logistics', 'Storage & Containers', 'Refrigerated Containers'): ('Refrigerated container',),
}

__all__ = ["RESEARCH_PATH_ALIASES"]
